# Installing TensorFlow
- To install TensorFlow on your local machine you can use pip.

In [ ]:
pip install tensorflow

- If you have a CUDA enabled GPU you can install the GPU version of TensorFlow. You will also need to install some other software which can be found here: https://www.tensorflow.org/install/gpu

In [ ]:
pip install tensorflow-gpu

In [ ]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

In [ ]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x


Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Type of tensor
- Variable
- Constant

In [ ]:
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(32,tf.int32)
floating = tf.Variable(3.567,tf.float32)

In [ ]:
rank1_tensor = tf.Variable(["This is rank one."],tf.string)
rank2_tensor = tf.Variable([[123,456],[789,456]],tf.int32)

In [ ]:
matrix = [[1,2,3,4,5],
      [6,7,8,9,10],
      [11,12,13,14,15],
      [16,17,18,19,20]]

tensor_matrix = tf.Variable(matrix,tf.int32)

<tf.Tensor: shape=(5, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]], dtype=int32)>

# Rank of tensor
- numpy = x, x means the rank of tensor

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of tensor

In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

# Reshape tensor


In [ ]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor1,[3,-1])#This will reshape to [3,2], -1 means that it caculates itself.

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
